version: '3.9'

services:

  shop-webapi:
    ports:
      - "5072:5072"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
